<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    $data = [];
    $data['scenes'] = [
        'black',
        'white',
        'hospital-bed',
        'hospital-hallway',
        'hospital-outside',
        'mc-room-day',
        'mc-room-dusk',
        'mc-room-night',
        'sarah-room-day',
        'sarah-room-dusk',
        'sarah-room-night',
        'house-kitchen-day',
        'house-kitchen-dusk',
        'house-kitchen-night',
        'carnival-day',
        'carnival-dusk',
        'carnival-night',
        'arcade-day',
        'arcade-dusk',
        'arcade-night',
        'restaurant-day',
        'restaurant-dusk',
        'restaurant-night',
        'cafe-inside-day',
        'cafe-inside-dusk',
        'cafe-inside-night',
        'cafe-entrance-day',
        'cafe-entrance-dusk',
        'cafe-entrance-night',
        'beach-day',
        'beach-dusk',
        'beach-night',
        'arcade-entrance-day',
        'arcade-entrance-dusk',
        'arcade-entrance-night',
        'farm-outside-day',
        'farm-outside-dusk',
        'farm-outside-night',
        'festival-day',
        'festival-dusk',
        'festival-night',
        'yutaka-shop-day',
        'baseball-entrance-day',
        'baseball-entrance-dusk',
        'baseball-entrance-night',
        'baseball-field-day',
        'baseball-field-dusk',
        'baseball-field-night',
        'soccer-entrance-day',
        'soccer-entrance-dusk',
        'soccer-entrance-night',
        'soccer-field-day',
        'soccer-field-dusk',
        'soccer-field-night',
        'train-day',
        'train-dusk',
        'train-night',
        'cab-day',
        'cab-dusk',
        'cab-night',
        'street-day',
        'street-dusk',
        'street-night',
        'planetarium-day',
        'planetarium-dusk',
        'planetarium-night',
        'graveyard-day',
        'graveyard-dusk',
        'graveyard-night',
        'forest-1-day',
        'forest-1-dusk',
        'forest-1-night',
        'forest-2-day',
        'forest-2-dusk',
        'forest-2-night',
        'amusement-inside-day',
        'amusement-inside-dusk',
        'amusement-inside-night',
        'amusement-entrance-day',
        'amusement-entrance-dusk',
        'amusement-entrance-night',
        'zoo-day',
        'zoo-dusk',
        'zoo-night',
        'garden-1-day',
        'garden-1-dusk',
        'garden-1-night',
        'garden-2-day',
        'garden-2-dusk',
        'garden-2-night',
    ];
    return view('welcome', $data);
});
